module.exports = {
	rules: {
		"no-loss-of-precision": "error",
		// Possible Errors
		"for-direction": "error",
		"getter-return": "error",
		"no-async-promise-executor": "error",
		"no-await-in-loop": "warn",
		"no-compare-neg-zero": "error",
		"no-cond-assign": "error",
		"no-console": "off",
		"no-constant-condition": ["error", { checkLoops: false }],
		"no-control-regex": "error",
		"no-debugger": "error",
		"no-dupe-args": "error",
		"no-dupe-else-if": "error",
		"no-dupe-keys": "error",
		"no-duplicate-case": "error",
		"no-empty": "error",
		"no-empty-character-class": "error",
		"no-ex-assign": "error",
		"no-extra-boolean-cast": "error",
		"no-extra-parens": "off",
		"no-extra-semi": "error",
		"no-func-assign": "error",
		"no-import-assign": "error",
		"no-inner-declarations": ["error", "both"],
		"no-invalid-regexp": "error",
		"no-irregular-whitespace": [
			"error",
			{
				skipStrings: false,
				skipComments: false,
				skipRegExps: false,
				skipTemplates: false
			}
		],
		"no-misleading-character-class": "error",
		"no-obj-calls": "error",
		"no-prototype-builtins": "warn",
		"no-regex-spaces": "warn",
		"no-setter-return": "error",
		"no-sparse-arrays": "error",
		"no-template-curly-in-string": "warn",
		"no-unexpected-multiline": "error",
		"no-unreachable": "error",
		"no-unsafe-finally": "error",
		"no-unsafe-negation": "error",
		"no-useless-backreference": "error",
		"require-atomic-updates": "error",
		"use-isnan": "error",
		"valid-typeof": "error",

		// Best Practices
		"accessor-pairs": [
			"error",
			{
				setWithoutGet: true,
				getWithoutSet: false,
				enforceForClassMembers: true
			}
		],
		"array-callback-return": "error",
		"block-scoped-var": "error",
		"class-methods-use-this": "off",
		"complexity": "off",
		"consistent-return": "warn",
		"curly": "error",
		"default-case": "off",
		"default-case-last": "error",
		"default-param-last": "off",
		"dot-location": ["error", "property"],
		"dot-notation": "error",
		"eqeqeq": ["error", "always", { null: "ignore" }],
		"grouped-accessor-pairs": "error",
		"guard-for-in": "off",
		"max-classes-per-file": "off",
		"no-alert": "warn",
		"no-caller": "error",
		"no-case-declarations": "error",
		"no-constructor-return": "warn",
		"no-div-regex": "off",
		"no-else-return": "off",
		"no-empty-function": "warn",
		"no-empty-pattern": "error",
		"no-eq-null": "off",
		"no-eval": "error",
		"no-extend-native": "error",
		"no-extra-bind": "warn",
		"no-extra-label": "off",
		"no-fallthrough": "error",
		"no-floating-decimal": "error",
		"no-global-assign": "error",
		"no-implicit-coercion": "off",
		"no-implicit-globals": "warn",
		"no-implied-eval": "error",
		"no-invalid-this": "error",
		"no-iterator": "error",
		"no-labels": "warn",
		"no-lone-blocks": "error",
		"no-loop-func": "warn",
		"no-magic-numbers": "off",
		"no-multi-spaces": "error",
		"no-multi-str": "warn",
		"no-new": "warn",
		"no-new-func": "off",
		"no-new-wrappers": "warn",
		"no-octal": "error",
		"no-octal-escape": "error",
		"no-param-reassign": "warn",
		"no-proto": "error",
		"no-redeclare": "error",
		"no-restricted-properties": "off",
		"no-return-assign": "error",
		"no-return-await": "off",
		"no-script-url": "warn",
		"no-self-assign": "error",
		"no-self-compare": "error",
		"no-sequences": "error",
		"no-throw-literal": "error",
		"no-unmodified-loop-condition": "error",
		"no-unused-expressions": ["warn", { allowShortCircuit: true, allowTernary: true }],
		"no-unused-labels": "error",
		"no-useless-call": "error",
		"no-useless-catch": "error",
		"no-useless-concat": "error",
		"no-useless-escape": "error",
		"no-useless-return": "error",
		"no-void": "error",
		"no-warning-comments": "off",
		"no-with": "error",
		"prefer-named-capture-group": "off",
		"prefer-promise-reject-errors": "error",
		"prefer-regex-literals": "error",
		"radix": "off",
		"require-await": "off",
		"require-unicode-regexp": "error",
		"vars-on-top": "off",
		"wrap-iife": ["error", "inside"],
		"yoda": "error",

		// Strict Mode
		"strict": "off",

		// Variables
		"init-declarations": "off",
		"no-delete-var": "error",
		"no-label-var": "error",
		"no-restricted-globals": "off",
		"no-shadow": "off",
		"no-shadow-restricted-names": "error",
		"no-undef": "error",
		"no-undef-init": "off",
		"no-undefined": "off",
		"no-unused-vars": ["error", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
		"no-use-before-define": "error",

		// Stylistic Issues
		"array-bracket-newline": ["error", "consistent"],
		"array-bracket-spacing": ["error", "never"],
		"array-element-newline": ["error", "consistent"],
		"block-spacing": "error",
		"brace-style": ["error", "1tbs", { allowSingleLine: true }],
		"camelcase": "error",
		"capitalized-comments": "off",
		"comma-dangle": "error",
		"comma-spacing": "error",
		"comma-style": "error",
		"computed-property-spacing": "error",
		"consistent-this": "off",
		"eol-last": "error",
		"func-call-spacing": "error",
		"func-name-matching": "warn",
		"func-names": ["warn", "as-needed"],
		"func-style": "error",
		"function-call-argument-newline": ["error", "consistent"],
		"function-paren-newline": ["error", "multiline-arguments"],
		"id-blacklist": "off",
		"id-length": "off",
		"id-match": "off",
		"implicit-arrow-linebreak": "error",
		"indent": ["error", "tab", { SwitchCase: 1 }],
		"jsx-quotes": ["error", "prefer-double"],
		"key-spacing": "error",
		"keyword-spacing": "error",
		"line-comment-position": "error",
		"linebreak-style": "off",
		"lines-around-comment": "off",
		"lines-between-class-members": ["error", "always", { exceptAfterSingleLine: true }],
		"max-depth": "off",
		"max-len": "off",
		"max-lines": "off",
		"max-lines-per-function": "off",
		"max-nested-callbacks": "off",
		"max-params": "off",
		"max-statements": "off",
		"max-statements-per-line": "off",
		"multiline-comment-style": "off",
		"multiline-ternary": "off",
		"new-cap": "off",
		"new-parens": "error",
		"newline-per-chained-call": "off",
		"no-array-constructor": "error",
		"no-bitwise": "off",
		"no-continue": "off",
		"no-inline-comments": "off",
		"no-lonely-if": "off",
		"no-mixed-operators": "off",
		"no-mixed-spaces-and-tabs": "error",
		"no-multi-assign": "warn",
		"no-multiple-empty-lines": "off",
		"no-negated-condition": "off",
		"no-nested-ternary": "off",
		"no-new-object": "error",
		"no-plusplus": "off",
		"no-restricted-syntax": "off",
		"no-tabs": "off",
		"no-ternary": "off",
		"no-trailing-spaces": "error",
		"no-underscore-dangle": "off",
		"no-unneeded-ternary": "error",
		"no-whitespace-before-property": "error",
		"nonblock-statement-body-position": "off",
		"object-curly-newline": "error",
		"object-curly-spacing": ["error", "always"],
		"object-property-newline": "off",
		"one-var": ["error", "never"],
		"one-var-declaration-per-line": "error",
		"operator-assignment": "error",
		"operator-linebreak": ["error", "after", { overrides: { "?": "before", ":": "before" } }],
		"padded-blocks": "off",
		"padding-line-between-statements": "off",
		"prefer-exponentiation-operator": "error",
		"prefer-object-spread": "error",
		"quote-props": ["error", "consistent-as-needed"],
		"quotes": ["error", "double"],
		"semi": "error",
		"semi-spacing": "error",
		"semi-style": "error",
		"sort-keys": "off",
		"sort-vars": "off",
		"space-before-blocks": "error",
		"space-before-function-paren": ["error", { anonymous: "never", named: "never" }],
		"space-in-parens": "error",
		"space-infix-ops": "error",
		"space-unary-ops": "error",
		"spaced-comment": "error",
		"switch-colon-spacing": "error",
		"template-tag-spacing": "error",
		"unicode-bom": "error",
		"wrap-regex": "error",

		// ECMAScript 6
		"arrow-body-style": ["error", "as-needed"],
		"arrow-parens": ["error", "as-needed"],
		"arrow-spacing": "error",
		"constructor-super": "error",
		"generator-star-spacing": ["error", { before: false, after: true }],
		"no-class-assign": "error",
		"no-confusing-arrow": "warn",
		"no-const-assign": "error",
		"no-dupe-class-members": "error",
		"no-duplicate-imports": "error",
		"no-new-symbol": "error",
		"no-restricted-exports": "off",
		"no-restricted-imports": "off",
		"no-this-before-super": "error",
		"no-useless-computed-key": "error",
		"no-useless-constructor": "error",
		"no-useless-rename": "error",
		"no-var": "error",
		"object-shorthand": "error",
		"prefer-arrow-callback": "error",
		"prefer-const": "error",
		"prefer-destructuring": "error",
		"prefer-numeric-literals": "error",
		"prefer-rest-params": "error",
		"prefer-spread": "error",
		"prefer-template": "error",
		"require-yield": "error",
		"rest-spread-spacing": "error",
		"sort-imports": "off",
		"symbol-description": "warn",
		"template-curly-spacing": "error",
		"yield-star-spacing": ["error", { before: false, after: true }]
	}
};
